# config/routes.yaml

home:
    path: /
    controller: App\Controller\HomeController::index


homme:
    path: /homme
    controller: App\Controller\ProductController::homme

femme:
    path: /femme
    controller: App\Controller\ProductController::femme

enfant:
    path: /enfant
    controller: App\Controller\ProductController::enfant

accessoire:
    path: /accessoire
    controller: App\Controller\HomeController::accessoire

panier:
    path: /panier
    controller: App\Controller\HomeController::panier

login:
    path: /login
    controller: App\Controller\HomeController::login

register:
    path: /register
    controller: App\Controller\HomeController::register